const RESOURCES = [
  ["tt-root","Teaching Tool — All files","Teaching Tool","folder","Project root","https://drive.google.com/drive/folders/1rWqZQ3bfW_bFrF3b05gvuURy-pCwc5v7","2026-07-12",["all","root","teaching"]],
  ["academic-root","Academic — All files","Academic","folder","Library root","https://drive.google.com/drive/folders/1RJI-7fzm-Zhd46XZaWl0fNfN3m69cWkd","2026-07-11",["all","root","academic"]],
  ["handbook-071","IB DP Chemistry Handbook — Draft v0.7.1","Teaching Tool","folder","Generated products","https://drive.google.com/drive/folders/1wQtogCItvJOFZ9gnbvPsbYDq3o9R-9Pi","2026-07-16T04:19:42Z",["IB","Chemistry","handbook","teacher","draft"]],
  ["ntk-index","NTK Master Index","Teaching Tool","sheet","NTK","https://docs.google.com/spreadsheets/d/1BmqcWhhZLN616rSzBbLquOm6pbFWzKLofQx0ZMy2zxw/edit","2026-07-14T15:33:15Z",["NTK","index","course","student"]],
  ["data-booklets","Physics Data Booklet Library","Academic","folder","Data booklets","https://drive.google.com/drive/folders/16c-QA8s2pLSFCE6ys7vkyvELTu9AmiFE","2026-07-16T01:51:39Z",["Physics","formula","equation","data booklet"]],
  ["comparison-zh","AQA GCSE vs CIE 0625 and Edexcel 4PH1 — zh-HK","Academic","pdf","Comparisons","https://drive.google.com/file/d/1cxJfiYHwuyJkn2R5gJbSYLj0mZEDdl6n/view","2026-07-15T02:11:15Z",["Physics","AQA","CIE","Edexcel","GCSE","comparison","zh-HK"]],
  ["comparison-en","AQA GCSE vs CIE 0625 and Edexcel 4PH1 — English","Academic","pdf","Comparisons","https://drive.google.com/file/d/1zvkEaWEIt1oA5vc-wTAYxQsdVFEyVyWo/view","2026-07-15T02:11:02Z",["Physics","AQA","CIE","Edexcel","GCSE","comparison","English"]],
  ["past-papers","Past Paper Workspace","Academic","folder","Past papers","https://drive.google.com/drive/folders/1QKbuVxAcym-fdHTZxGM5tWe2q3g84o6w","2026-07-15T09:55:01Z",["past paper","originals","catalog","analysis","upload"]],
  ["past-upload","Past Papers — Upload Here","Academic","folder","Past papers","https://drive.google.com/drive/folders/1kaaebqt9TsQ_IsYcFTwCBFIrHXuoBXqC","2026-07-15T09:55:08Z",["past paper","upload","inbox"]],
  ["syllabus","Syllabus Library","Academic","folder","Syllabus","https://drive.google.com/drive/folders/18m4prgYM_E1f_ehlK7h_6EQyQWY0zPFt","2026-07-11",["syllabus","IB","A-Level","IGCSE","GCSE","AP","HKDSE"]],
  ["academic-comparisons","Academic Comparisons","Academic","folder","Comparisons","https://drive.google.com/drive/folders/1o2e4CYX2KKmi89uoX4pD31y6LEETcHYy","2026-07-15",["comparison","coverage","teacher"]],
  ["ntk","NTK Library","Teaching Tool","folder","NTK","https://drive.google.com/drive/folders/1rabmE6uIN4_sbW4qlCSJTBzJpmXzDE3E","2026-07-14T15:27:48Z",["NTK","course","exercise","quiz"]],
  ["summer","NTK 2026–2027 Summer CO","Teaching Tool","folder","NTK","https://drive.google.com/drive/folders/1Y5NoMEG8WSDn8B3nRg99AFiWckND4xka","2026-07-14T15:28:07Z",["NTK","Summer CO","2026","2027"]],
  ["summer-gceas","Summer CO — Physics GCE AS","Teaching Tool","folder","NTK","https://drive.google.com/drive/folders/1a8Ea-vV1dTOH2w2N19-8GuGoB-1NSDeN","2026-07-16T00:46:30Z",["NTK","Physics","GCE AS","quiz","exercise"]],
  ["summer-ibh2","Summer CO — Physics IB HL2","Teaching Tool","folder","NTK","https://drive.google.com/drive/folders/1vpWLCwsLR9G3NlxXYt7x8B0sLaxhNX-o","2026-07-14T16:29:35Z",["NTK","Physics","IB","HL2","quiz","exercise"]],
  ["pl","NTK 2026–2027 Private Lessons","Teaching Tool","folder","NTK","https://drive.google.com/drive/folders/12Z69X3sq4X8NgM_hscRQ3zxp2QxVmAgL","2026-07-14T15:28:18Z",["NTK","PL","private lesson","student"]],
  ["ia","IB IA Analyser","Teaching Tool","folder","Tools","https://drive.google.com/drive/folders/18KXsbh3BeDdXypIy_e_TBP9u9wUoo1Ru","2026-07-14T03:31:56Z",["IB","Physics","IA","analysis","report"]],
  ["products","Generated Products","Teaching Tool","folder","Generated products","https://drive.google.com/drive/folders/14vYLAlN5EXAwOzpd8DoF8wvQDLz5L_GB","2026-07-12",["products","draft","approved","published"]],
  ["drafts","Generated Products — Draft","Teaching Tool","folder","Generated products","https://drive.google.com/drive/folders/1svD_kG4sOMIiYchygiKDJHV5CnbgOGSM","2026-07-12",["products","draft","handbook","notes"]],
  ["pilot","Four-Product Pilot — P9-D","Teaching Tool","folder","Generated products","https://drive.google.com/drive/folders/1lGUeoHb6rAKVl2ANqHzf6JcxX2Z5-UKa","2026-07-14T09:31:12Z",["pilot","teaching note","revision","exercise","quiz"]],

  ["handbook-pdf","IB DP Chemistry 2025 — Visual-First Teacher Revision Handbook v0.7.1","Teaching Tool","pdf","Chemistry handbook","https://drive.google.com/file/d/1Di0KnxYHpJ2SX1jz6WdtEQQyimmgUM_2/view","2026-07-16T04:21:23Z",["IB","Chemistry","handbook","teacher","colour","current"]],
  ["handbook-gray","IB DP Chemistry 2025 — Teacher Revision Handbook v0.7.1 — Grayscale","Teaching Tool","pdf","Chemistry handbook","https://drive.google.com/file/d/1UOj0HGNZ-DmpEbpGGpnmZNbiTPV-xpKn/view","2026-07-16T04:21:42Z",["IB","Chemistry","handbook","teacher","grayscale","print"]],
  ["pl-projectile-student","Exercise 01 — Projectile Motion — Student v2.0","Teaching Tool","pdf","NTK · PL · IBHL · Topic A","https://drive.google.com/file/d/1nw7dcdV2wbumv5CtGqKWP_QpgZSPTBmf/view","2026-07-17T03:33:02Z",["Physics","IB","projectile motion","student","exercise","PL","current"]],
  ["pl-projectile-teacher","Exercise 01 — Projectile Motion — Teacher v2.0","Teaching Tool","pdf","NTK · PL · IBHL · Topic A","https://drive.google.com/file/d/1316t2bMlXtpVFnRge8TTYUcKPXeATZAW/view","2026-07-17T03:32:50Z",["Physics","IB","projectile motion","teacher","markscheme","exercise","PL","current"]],
  ["ibh2-fields-student","Exercise 01 — Fields — Student v1.0","Teaching Tool","pdf","NTK · Summer CO · IB HL2 · MOD B","https://drive.google.com/file/d/1xlKRi3n4JJi2FQBsuFhBEyiGj_kmDTwA/view","2026-07-17T03:30:37Z",["Physics","IB","HL2","fields","student","exercise","current"]],
  ["ibh2-fields-teacher","Exercise 01 — Fields — Teacher v1.0","Teaching Tool","pdf","NTK · Summer CO · IB HL2 · MOD B","https://drive.google.com/file/d/1UKr_pr7KT1sHaS-tpt5nVr_q4NiKM7Px/view","2026-07-17T03:30:25Z",["Physics","IB","HL2","fields","teacher","markscheme","exercise","current"]],
  ["ibh2-em-student","Exercise 02 — Motion in Electromagnetic Fields — Student v1.0","Teaching Tool","pdf","NTK · Summer CO · IB HL2 · MOD B","https://drive.google.com/file/d/1OcQOpE2aQkjtFWApl3mNlBPsFzjsnHqC/view","2026-07-17T03:29:58Z",["Physics","IB","HL2","electric","magnetic","student","exercise","current"]],
  ["ibh2-em-teacher","Exercise 02 — Motion in Electromagnetic Fields — Teacher v1.0","Teaching Tool","pdf","NTK · Summer CO · IB HL2 · MOD B","https://drive.google.com/file/d/1wgya539GRQkpPTm6v1aZMKpYNiNUFnBT/view","2026-07-17T03:29:48Z",["Physics","IB","HL2","electric","magnetic","teacher","markscheme","exercise","current"]],
  ["ibh2-quiz-student","Quiz 01 — Fields & Charged-Particle Motion — Student v1.0","Teaching Tool","pdf","NTK · Summer CO · IB HL2 · MOD B","https://drive.google.com/file/d/1ODlfwwk9kQauLgL-E__42TYkrW-bDIfs/view","2026-07-17T03:34:19Z",["Physics","IB","HL2","fields","charged particle","student","quiz","current"]],
  ["ibh2-quiz-teacher","Quiz 01 — Fields & Charged-Particle Motion — Teacher v1.0","Teaching Tool","pdf","NTK · Summer CO · IB HL2 · MOD B","https://drive.google.com/file/d/1uZnO_cszebvjGaUneBz4UCA2yKnb1Bsc/view","2026-07-17T03:34:11Z",["Physics","IB","HL2","fields","charged particle","teacher","markscheme","quiz","current"]],
  ["gceas-quiz-student","Quiz 01B — Kinematics & Projectile Motion — Student v1.0","Teaching Tool","pdf","NTK · Summer CO · GCE AS · MOD A","https://drive.google.com/file/d/1wK3kEqmAnLwaN33X4ff14hqNGYi5nknf/view","2026-07-17T03:35:35Z",["Physics","GCE","AS","kinematics","projectile motion","student","quiz","current"]],
  ["gceas-quiz-teacher","Quiz 01B — Kinematics & Projectile Motion — Teacher v1.0","Teaching Tool","pdf","NTK · Summer CO · GCE AS · MOD A","https://drive.google.com/file/d/182M_U2gbYsiuyGaKHdtbYVHwV_PyV1Oh/view","2026-07-17T03:35:26Z",["Physics","GCE","AS","kinematics","projectile motion","teacher","markscheme","quiz","current"]],
  ["ibh2-thermal-ex","Exercise 02 — Thermal Physics — Combined Draft v1.0","Teaching Tool","pdf","NTK · Summer CO · IB HL2 · MOD A","https://drive.google.com/file/d/1LDGf7SDTC7_cGpVLTpIAV2PYNmRQKfA7/view","2026-07-17T03:30:46Z",["Physics","IB","HL2","thermal","exercise","combined","draft"]],
  ["ibh2-thermal-quiz","Quiz 01 — Thermal Physics — Combined Draft v1.0","Teaching Tool","pdf","NTK · Summer CO · IB HL2 · MOD A","https://drive.google.com/file/d/1n1Ia3jA4AzuS--oNp7coPggEoY8wVtun/view","2026-07-17T03:30:56Z",["Physics","IB","HL2","thermal","quiz","combined","draft"]],
  ["pilot-resistance-student","Teaching Note 01 — Resistance — Student","Teaching Tool","pdf","Four-Product Pilot","https://drive.google.com/file/d/1V06_b648vLbQ8yV_jtmwTQHBG8qmdQRa/view","2026-07-17T03:37:59Z",["Physics","CIE","0625","resistance","student","teaching note","pilot"]],
  ["pilot-electrolysis-student","Exercise 03 — Electrolysis — Student","Teaching Tool","pdf","Four-Product Pilot","https://drive.google.com/file/d/1dN-w1aTz2y4ivM5Y2hHKSiD2j8M3yI_Z/view","2026-07-17T03:37:42Z",["Chemistry","CIE","0620","electrolysis","student","exercise","pilot"]],
  ["pilot-electrolysis-teacher","Exercise 03 — Electrolysis — Teacher","Teaching Tool","pdf","Four-Product Pilot","https://drive.google.com/file/d/15X6Qcj_hMSiQ13DZDCY-uQ0I8PFUVU_U/view","2026-07-17T03:37:32Z",["Chemistry","CIE","0620","electrolysis","teacher","markscheme","exercise","pilot"]],
  ["pilot-shm-student","Quiz 04 — Simple Harmonic Motion — Student","Teaching Tool","pdf","Four-Product Pilot","https://drive.google.com/file/d/14wV_MTLKrOMhPraAFtmxCBnPneg90Ebt/view","2026-07-17T03:37:24Z",["Physics","IB","HL","SHM","simple harmonic motion","student","quiz","pilot"]],
  ["pilot-shm-teacher","Quiz 04 — Simple Harmonic Motion — Teacher","Teaching Tool","pdf","Four-Product Pilot","https://drive.google.com/file/d/1Kai-G6inBLDpXHbz4Nb0k72dugBQW8wu/view","2026-07-17T03:37:17Z",["Physics","IB","HL","SHM","simple harmonic motion","teacher","markscheme","quiz","pilot"]]
].map(([id,title,source,kind,group,url,created,tags])=>({id,title,source,kind,group,url,created,tags}));

const ICON={folder:"▰",pdf:"PDF",doc:"DOC",sheet:"SHT",json:"{ }"};
const state={query:"",view:"Home",showAll:false,favourites:JSON.parse(localStorage.getItem("teaching-hub-favourites")||"[]")};
const byId=id=>RESOURCES.find(item=>item.id===id);
const esc=value=>String(value).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const fmt=value=>new Intl.DateTimeFormat("en-GB",{day:"2-digit",month:"short"}).format(new Date(value));
const academic=byId("academic-root"), teaching=byId("tt-root");

function filtered(){
  const needle=state.query.trim().toLowerCase();
  return RESOURCES.filter(item=>{
    const inView=state.view==="Home"||(state.view==="Favourites"?state.favourites.includes(item.id):state.view==="Files"?item.kind!=="folder":item.source===state.view);
    const text=[item.title,item.source,item.kind,item.group,...item.tags].join(" ").toLowerCase();
    return inView&&(!needle||text.includes(needle));
  }).sort((a,b)=>new Date(b.created)-new Date(a.created));
}
function card(item){return `<article class="resource-card"><div class="file-icon ${item.kind}">${ICON[item.kind]}</div><div class="card-copy"><p>${item.source} · ${fmt(item.created)}</p><h3>${esc(item.title)}</h3><span>${esc(item.group)}</span></div><button class="star ${state.favourites.includes(item.id)?"selected":""}" data-fav="${item.id}" aria-label="Toggle favourite">★</button><a class="card-open" href="${item.url}" target="_blank" rel="noreferrer">Open ↗</a></article>`}
function row(item){return `<div class="compact-row"><div class="mini-icon ${item.kind}">${ICON[item.kind]}</div><a href="${item.url}" target="_blank" rel="noreferrer"><b>${esc(item.title)}</b><span>${item.source} · ${esc(item.group)}</span></a><span class="row-date">${fmt(item.created)}</span><button class="star ${state.favourites.includes(item.id)?"selected":""}" data-fav="${item.id}" aria-label="Toggle favourite">★</button><a class="open-icon" href="${item.url}" target="_blank" rel="noreferrer" aria-label="Open ${esc(item.title)}">↗</a></div>`}
function heading(eyebrow,title,button=""){return `<div class="section-heading"><div><p class="eyebrow">${eyebrow}</p><h2>${title}</h2></div>${button}</div>`}

function render(){
  const visible=filtered(), recent=RESOURCES.filter(x=>x.kind!=="folder").sort((a,b)=>new Date(b.created)-new Date(a.created)).slice(0,5);
  const favourites=RESOURCES.filter(x=>state.favourites.includes(x.id));
  const list=(state.showAll||state.query||state.view!=="Home")?visible:visible.slice(0,12);
  const home=state.view==="Home"&&!state.query?`<section class="welcome"><div><p class="eyebrow">PRIVATE RESOURCE INDEX</p><h1>Find a file. Open it.</h1><p>Direct shortcuts to the useful parts of Academic and Teaching Tool.</p></div><div class="source-actions"><a href="${academic.url}" target="_blank"><b>Academic</b><span>Syllabus, papers, data booklets ↗</span></a><a href="${teaching.url}" target="_blank"><b>Teaching Tool</b><span>Products, NTK, rules and tools ↗</span></a></div></section><section>${heading("NEWEST FIRST","Recent additions")}<div class="recent-grid">${recent.map(card).join("")}</div></section><section>${heading("SAVED ON THIS DEVICE","My favourites")}${favourites.length?`<div class="compact-list">${favourites.map(row).join("")}</div>`:`<button class="empty-state" data-first-fav>No favourites yet. Add NTK Master Index as the first one.</button>`}</section>`:"";
  const rootUrl=state.view==="Academic"?academic.url:teaching.url;
  document.querySelector("#app").innerHTML=`<div class="app-shell"><aside class="sidebar"><div class="brand"><span class="brand-mark">T</span><span>Teaching<br>Product Hub</span></div><nav aria-label="Primary navigation">${["Home","Files","Academic","Teaching Tool","Favourites"].map(item=>`<button class="nav-item ${state.view===item?"active":""}" data-view="${item}"><span>${item==="Home"?"⌂":item==="Files"?"▤":item==="Academic"?"A":item==="Teaching Tool"?"T":"★"}</span>${item}${item==="Favourites"?`<b>${state.favourites.length}</b>`:""}</button>`).join("")}</nav><div class="side-divider"></div><p class="side-label">One-click access</p><a class="side-link" href="${academic.url}" target="_blank">Academic — all files <span>↗</span></a><a class="side-link" href="${teaching.url}" target="_blank">Teaching Tool — all files <span>↗</span></a><a class="side-link" href="${byId("ntk-index").url}" target="_blank">NTK Master Index <span>↗</span></a><p class="side-note">Only useful products and current files are indexed. Backend, source, validation and legacy items are hidden.</p></aside><main><header class="topbar"><div class="search-wrap"><span>⌕</span><input id="search" value="${esc(state.query)}" placeholder="Search title, topic, board, Student or Teacher" aria-label="Search resources"><kbd>⌘ K</kbd></div>${state.query?`<a class="drive-search" href="https://drive.google.com/drive/u/0/search?q=${encodeURIComponent(state.query)}" target="_blank">Search full Drive ↗</a>`:`<a class="root-button" href="${rootUrl}" target="_blank">Open folder ↗</a>`}</header><div class="content">${home}<section class="library-section">${heading(state.query?`${visible.length} INDEXED MATCHES`:"QUICK INDEX",state.query?`Search results for “${esc(state.query)}”`:state.view==="Home"?"All indexed shortcuts":state.view,state.view==="Home"&&!state.query?`<button class="text-button" data-show-all>${state.showAll?"Show less":"Show all"}</button>`:"")}${list.length?`<div class="compact-list">${list.map(row).join("")}</div>`:`<div class="no-results"><b>No matching indexed shortcut</b><span>Use “Search full Drive” above to search every file you can access.</span></div>`}</section></div></main></div>`;
  bind();
}
function toggle(id){state.favourites=state.favourites.includes(id)?state.favourites.filter(x=>x!==id):[...state.favourites,id];localStorage.setItem("teaching-hub-favourites",JSON.stringify(state.favourites));render()}
function bind(){
  document.querySelectorAll("[data-view]").forEach(el=>el.onclick=()=>{state.view=el.dataset.view;state.query="";render()});
  document.querySelectorAll("[data-fav]").forEach(el=>el.onclick=()=>toggle(el.dataset.fav));
  document.querySelector("[data-first-fav]")?.addEventListener("click",()=>toggle("ntk-index"));
  document.querySelector("[data-show-all]")?.addEventListener("click",()=>{state.showAll=!state.showAll;render()});
  const search=document.querySelector("#search"); search.oninput=e=>{const pos=e.target.selectionStart;state.query=e.target.value;render();const next=document.querySelector("#search");next.focus();next.setSelectionRange(pos,pos)};
}
document.addEventListener("keydown",event=>{if((event.metaKey||event.ctrlKey)&&event.key.toLowerCase()==="k"){event.preventDefault();document.querySelector("#search")?.focus()}});
render();
